export enum LightThemeSchemaColors {
  WHITE = "#ffffff",
  BLACK = "#000000",
  PRIMARY_BACKGROUND = "#f6f9fc",
  SECONDARY_BACKGROUND = "#004666",

  PRIMARY_TEXT_COLOR = "#f6f9fc",
  SECONDARY_TEXT_COLOR = "#000000",

  TOP_NAV_BAR_BACKGROUND = "#0F3460",
  TOP_NAV_BAR_TEXT = "#FFFFFF",
  TOP_NAV_DROPDOWN_TEXT_COLOR = "#0F3460",
}
